collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4279713032301515
color:
  saturation: 0.718638
  brandStrength: 0.3305992565583438
  rhythmicContrast: 0.2144172
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  lightness: 0.6541219
layout_spectrum: 0.9426523
name: Wedding of Juracy & David
