collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3189131636172533
color:
  saturation: 0.8350996894296259
  brandStrength: 0.03823572373948991
  rhythmicContrast: 0.8914094709325582
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  lightness: 0.2532398053444922
layout_spectrum: 0.41627442254684865
name: Wedding of Juracy & David
