collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4210222
  brandStrength: 1
  lightness: 0.780274
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  rhythmicContrast: 0.8225806
typography_spectrum: 0.7258065
layout_spectrum: 0.9175627
name: Juracy&David
